name: AE Docs Updater Program Run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get build run ID
        run: echo "BUILD_RUN_ID=$(gh run list --json databaseId --workflow=build.yml --limit 1 | jq -r '.[0].databaseId')" >> $GITHUB_ENV
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ env.BUILD_RUN_ID }}
          github-token: $GH_TOKEN
      - name: Run program
        env:
          GH_ACCESS_TOKEN: $GH_TOKEN
        run: |
          git config user.name "GitHub Docs Updater Program Build Bot"
          git config user.email "<>"
          chmod u+wrx program
          ./program
