name: AE Docs Updater Program Runner
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set GH_ACCESS_TOKEN
        run: export GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
      - name: Run program
        run: ./program
