name: AE Docs Updater Program Run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  run:
    env:
      GH_TOKEN: ${{ github.token }}
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Get build run ID
        run: BUILD_RUN_ID=$(gh run list --repo ${{ github.repository }} --json databaseId --workflow=build.yml --limit 1 | jq -r '.[0].databaseId')
      - run: echo $BUILD_RUN_ID
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: $BUILD_RUN_ID
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Run program
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          git config user.name "GitHub Docs Updater Program Build Bot"
          git config user.email "<>"
          ./program
