name: AE Docs Updater Program Run
on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set GitHub user
        run: |
          git config user.name "GitHub Docs Updater Program Build Bot"
          git config user.email "<>"
      - name: Run program
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: ./program
