name: AE Docs Updater Program Run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Run program
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          git config user.name "GitHub Docs Updater Program Build Bot"
          git config user.email "<>"
          ./program
