name: AE Docs Updater Program Runner
on:
  push:
    branches: [master]
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: ./program
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN  }}
