name: AE Docs Updater Program Runner
on:
  push:
    branches: [master]

jobs:
  run:
    name: Run Docs Updater Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run program
        run: GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN  }} ./program
